try:
    from fis.core import Core
    c = Core()
except Exception as e:
    print('ERROR: ', e)
